const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{platforms: 0},
	{Tomato: 0},
	{Keyboard: 0},
	{forest: 0},
	{frigHp: 0},
	{Frig: 0},
	{Ded: 0},
	{tomatoBlocker: 0},
	{Sword: 0},
	{Sprite2: 0},
	{collison1: 0},
	{Sprite3: 0},
	{StartButton: 0},
	{Settings: 0},
	{Mouse: 0},
	{Sprite6: 0},
	{Text: 0},
	{Anchor: 0},
	{Orbs: 0},
	{SwordPrompt: 0},
	{Tacquired: 0},
	{Health: 0},
	{Dead: 0},
	{selectStart: 0},
	{selectSettings: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	platforms: class extends self.ITiledBackgroundInstance {},
	Tomato: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	forest: class extends self.ITiledBackgroundInstance {},
	Frig: class extends self.ISpriteInstance {},
	Ded: class extends self.ITiledBackgroundInstance {},
	tomatoBlocker: class extends self.ITiledBackgroundInstance {},
	Sword: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	collison1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Orbs: class extends self.ISpriteInstance {},
	SwordPrompt: class extends self.ITextInstance {}
}