const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{platforms: 0},
	{Tomato: 0},
	{Keyboard: 0},
	{forest: 0},
	{frigHp: 0},
	{Frig: 0},
	{Ded: 0},
	{tomatoBlocker: 0},
	{Sword: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{collison1: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Mouse: 0},
	{Tacquired: 0},
	{Health: 0},
	{Dead: 0},
	{selectStart: 0},
	{selectSettings: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	platforms: class extends self.ITiledBackgroundInstance {},
	Tomato: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	forest: class extends self.ITiledBackgroundInstance {},
	Frig: class extends self.ISpriteInstance {},
	Ded: class extends self.ITiledBackgroundInstance {},
	tomatoBlocker: class extends self.ITiledBackgroundInstance {},
	Sword: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	collison1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}